language: objective-c
osx_image: xcode8.2
before_install:
  - gem update --system
  - gem install fastlane --no-rdoc --no-ri --no-document --quiet
install: true
script:
  - fastlane --version
before_deploy:
  - gem update fastlane
deploy:
  skip_cleanup: true
  provider: script
  script:
    - fastlane --version
  on:
    branch: master
